import express from 'express';
import * as authController from "../Controller/authController.js";
const app = express();
import { asyncHandler } from '../Middleware/errorHandling.js';
import validation from '../Middleware/validation.js';
import { signinSchema, signupSchema } from '../Validation/authValidation.js';
app.post("/signup", validation(signupSchema), asyncHandler(authController.signup));
app.post("/signin", validation(signinSchema), asyncHandler(authController.signin));
app.put("/confirmEmail/:token", asyncHandler(authController.confirmEmail));
app.put("/newConfirmEmail/:RefreshToken", asyncHandler(authController.newConfirmEmail));
export default app;